//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresSoins
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OracleSoinEntities : DbContext
    {
        public OracleSoinEntities()
            : base("name=OracleSoinEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DOSSIER> DOSSIERs { get; set; }
        public virtual DbSet<INTERVENANT> INTERVENANTs { get; set; }
        public virtual DbSet<INTERVENANTEXTERNE> INTERVENANTEXTERNEs { get; set; }
        public virtual DbSet<PRESTATION> PRESTATIONs { get; set; }
    }
}
