//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresSoins
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTERVENANTEXTERNE
    {
        public decimal ID { get; set; }
        public string SPECIALITE { get; set; }
        public string ADRESSE { get; set; }
        public string TEL { get; set; }
    
        public virtual INTERVENANT INTERVENANT { get; set; }
    }
}
