//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresSoins
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTERVENANT
    {
        public decimal ID { get; set; }
        public string NOM { get; set; }
        public string PRENOM { get; set; }
    }
}
