//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresSoins
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTERVENANT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INTERVENANT()
        {
            this.PRESTATIONs = new HashSet<PRESTATION>();
        }
    
        public decimal ID { get; set; }
        public string NOM { get; set; }
        public string PRENOM { get; set; }
    
        public virtual INTERVENANTEXTERNE INTERVENANTEXTERNE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRESTATION> PRESTATIONs { get; set; }
    }
}
