//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresSoins
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRESTATION
    {
        public decimal ID { get; set; }
        public string NOM { get; set; }
        public System.DateTime DATEPRESTATION { get; set; }
        public decimal IDDOSSIER { get; set; }
        public decimal IDINTERVENANT { get; set; }
    
        public virtual DOSSIER DOSSIER { get; set; }
        public virtual INTERVENANT INTERVENANT { get; set; }
    }
}
